name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build cadc-java
      run: cd cadc-java && DOCKER_CONTENT_TRUST=1 docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag cadc-tomcat:$(date +%s) .
    
    - name: Build cadc-tomcat
      run: cd cadc-tomcat && DOCKER_CONTENT_TRUST=1 docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag cadc-tomcat:$(date +%s) .
    
    - name: Build cadc-haproxy-dev
      run: cd cadc-haproxy-dev && DOCKER_CONTENT_TRUST=1 docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag cadc-tomcat:$(date +%s) .

    # cadc-postgresql-dev requires a pgsphere rpm which is currently available for amd64 only
    # cadc-postgresql-dev/Dockerfile hard-coded to install the x86_64 postgresql repository and pgsphere rpm
    - name: Build cadc-postgresql-dev
      run: cd cadc-postgresql-dev && DOCKER_CONTENT_TRUST=1 docker docker buildx build --platform linux/amd64 --file Dockerfile --tag cadc-tomcat:$(date +%s) .
    
